[features]
seeds = false
[programs.localnet]
sol_idempotent = "id7Fj1ywco2RdzTcQFNcYxf6Wu9iJZeNPtQY9xdsw87"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lando/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
